 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crash_data_v1_development
 
test:
  <<: *default
  database: crash_data_v1_test
 
production:
  <<: *default
  database: crash_data_v1_production
  username: crash_data_v1
  password: <%= ENV['SWT-V3_DATABASE_PASSWORD'] %>
